---
title: "nih_table.Rmd"
author: "Peter Higgins"
date: "7/20/2018"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(flextable)
library(here)
library(writexl)
library(magrittr)
library(knitr)
library(rmarkdown)
library(officer)
library(weasydoc)
```

## Read in data and clean up
```{r read_clean}

ibd <- read_csv("IBDDatabank2015_DATA_2018-06-29_0901.csv")

ibd %>% 
  filter(redcap_event_name == "baseline_visit_arm_1") %>% 
  select(sex, race___0:ethnicity) %>% 
  mutate(race  =  case_when(
             .$race___0 == 1 ~ "White",
             .$race___1 == 1 ~ "Black or African-American",
             .$race___2 == 1 ~ "Asian",
             .$race___3 == 1 ~ "Native Hawaiian or Other Pacific Islander",
             .$race___4 == 1 ~ "American Indian or Alaska Native",
             .$race___5 == 1 ~ "More Than One Race",
             .$race___999 == 1 ~ "Unknown or Not Reported",
             TRUE ~ "Unknown or Not Reported")) %>% 
  select(sex, race, ethnicity) %>% 
  mutate(ethnic_cat = case_when(
    .$ethnicity == 1 ~ "Hispanic or Latino",
    .$ethnicity == 0 ~ "Not Hispanic or Latino",
    TRUE ~ "Unknown or Not Reported Ethnicity")) %>% 
  select(sex, race, ethnic_cat) %>% 
  mutate(sex2 = case_when(
    .$sex == 1 ~ "Male",
    .$sex == 0 ~ "Female",
    TRUE ~ "Female")) %>% 
  select(sex2, race, ethnic_cat) ->
ibd

ibd_table <- ibd %>% 
  tabyl(race, sex2, ethnic_cat) %>% 
  reduce(left_join, by = "race")

names(ibd_table) <-(c("race", "female.Hispanic", 
                      "male.Hispanic", 
        "female.Not", "male.Not",
        "female.Unknown", "male.Unknown"))

ibd_table2 <- gather(ibd_table, key= sex.eth, value = count, -race) %>% 
  separate(sex.eth, into = c('sex', 'ethnicity')) %>% 
  filter(count != 0)
```


Now create an empty table with zeroes in all possible 63 cells.

```{r empty}

l <- list(race = 
            c("White",
              "Black or African-American",
              "Asian",
              "Native Hawaiian or Other Pacific Islander",
              "American Indian or Alaska Native",
              "More Than One Race",
              "Unknown or Not Reported"),
          sex = c("male",
                  "female",
                  "Unknown or Not Reported Sex",
                  "male",
                  "female",
                  "male",
                  "female"),
          ethnicity = c("Hispanic",
                        "Not",
                        "Unknown",
                        "Hispanic",
                        "Not",
                        "Hispanic",
                        "Not"),
          count = rep(0,7))
empty_table <- as_tibble(l) %>% 
        tidyr::complete(race, 
                nesting(sex), nesting(ethnicity),fill=list(count = 0))


```

## Now anti-join



```{r anti_join, echo=TRUE}
# now anti-join ibd_table2 with empty_table to get missing rows
# with no counts in our sample
complement <- anti_join(empty_table, ibd_table2, by = c('race', 'sex', "ethnicity")) %>% 
  print(n=Inf)
```

## Now bind with complement

```{r combine}
# now combine complement with ibd_table2
full_table <- bind_rows(ibd_table2, complement)

```

## Set up to Spread
```{r spread}
# set up to spread
ibd_table <- full_table %>% 
  unite(col = "eth.sex", c('ethnicity', "sex"), sep=".") %>% 
  spread(key = eth.sex, value = count) 
```

## Now add margin totals and arrange, write xls
```{r margin_totals}

# convert race col to rownames to make numbers into a matrix
m <- as.matrix(ibd_table[ ,-1])
rownames(m) <- ibd_table$race
ibd_table2 <- addmargins(m, FUN=c(Total=sum), quiet = T)
ibd_table <- rownames_to_column(as.data.frame(ibd_table2), "Racial Categories")

#arrange without total
ibd_table3 <- ibd_table[1:7,] %>% arrange(`Racial Categories`)

ibd_table <- as.data.frame(rbind(ibd_table3, ibd_table[8,]))

write_xlsx(ibd_table, here("ibd_table.xlsx"))

```

## Now make flextable
```{r flextable, echo=TRUE}
#make flextable
myft <- ibd_table %>% 
  regulartable() %>% 
  theme_booktabs() %>% 
  set_formatter_type(fmt_double = "%0.0f") %>% 
  add_header(`Racial Categories` = "Racial Categories",
             Hispanic.female = "Hispanic or Latino",
             Hispanic.male = "Hispanic or Latino",
             `Hispanic.Unknown or Not Reported Sex` = "Hispanic or Latino",
             Not.female = "Not Hispanic or Latino",
             Not.male = "Not Hispanic or Latino",
             `Not.Unknown or Not Reported Sex` = "Not Hispanic or Latino",
             Unknown.female = "Unknown/Not Reported",
             Unknown.male = "Unknown/Not Reported",
             `Unknown.Unknown or Not Reported Sex` = "Unknown/Not Reported",
             Total = "Total") %>% 
  add_header(`Racial Categories` = "Racial Categories",
             Hispanic.female = "Ethnic Categories Divided by Sex",
             Hispanic.male = "Ethnic Categories Divided by Sex",
             `Hispanic.Unknown or Not Reported Sex` = "Ethnic Categories Divided by Sex",
             Not.female = "Ethnic Categories Divided by Sex",
             Not.male = "Ethnic Categories Divided by Sex",
             `Not.Unknown or Not Reported Sex` = "Ethnic Categories Divided by Sex",
             Unknown.female = "Ethnic Categories Divided by Sex",
             Unknown.male = "Ethnic Categories Divided by Sex",
             `Unknown.Unknown or Not Reported Sex` = "Ethnic Categories Divided by Sex",
             Total = "Total") %>% 
  set_header_labels(`Racial Categories` = "Racial Categories",
                    Hispanic.female = "Female",
                    Hispanic.male = "Male",
                    `Hispanic.Unknown or Not Reported Sex` = "Unknown",
                    Not.female = "Female",
                    Not.male = "Male",
                    `Not.Unknown or Not Reported Sex` = "Unknown",
                    Unknown.female = "Female",
                    Unknown.male = "Male",
                    `Unknown.Unknown or Not Reported Sex` = "Unknown",
                    Total = "Total") %>% 
  font(fontname = "Arial") %>% 
  fontsize(size = 9) %>% 
  fontsize(size=11, part="header") %>% 
  merge_h(part= "header") %>% 
  merge_v(part= "header") %>% 
  align(align = "center", part = "all") %>% 
  width(j = 1, width = 2.0)

myft
```

